version: "3.8"

services:
    # Service Aplikasi Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "8080:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=database
            - DB_PORT=3306
            - SESSION_DOMAIN
            - SESSION_DRIVER=file
            - DB_DATABASE=pariwisataku
            - DB_USERNAME=root
            - DB_PASSWORD=Pariwisataku123!
        networks:
            - laravel_network

networks:
    laravel_network:
        name: laravel_network
        driver: bridge